--- #YAML:1.0
name: Win32-PerfLib
abstract: Accessing the Windows NT Performance Counter
version: 0.07
author:
  - Jutta M. Klebe <jmk@bybyte.de>
  - Jan Dubois <jand@activestate.com>
license: perl
requires: 
  perl: 5.006
resources:
  license: http://dev.perl.org/licenses/
  repository: https://github.com/jandubois/win32-perflib
meta-spec:
   version: 1.3
   url: http://module-build.sourceforge.net/META-spec-v1.3.html
generated_by: Jan Dubois
